### ISSUE TITLE
Fail to build ng5 --prod app

### ISSUE THREAD

**Issue by alcasas** [Enlcxx/angular2-resizing-cropping-image#10]
Hello, when I try to build my ng5 app with --prod flag I'm getting something like this:

`ERROR in : Unexpected value 'LyResizingCroppingImageModule in /Users/username/Documents/projectname/node_modules/angular2-resizing-cropping-image/index.d.ts' imported by the module 'MyModule in /Users/username/Documents/software-projectname/src/app/my-module/MyModule.module.ts'. Please add a @NgModule annotation.`

Could you update it or tell me how to fix it?

**Comment by alyleui** [comment]
Hi!
This repository is now in https://github.com/A-l-y-l-e/Alyle-UI/pull/10
[demo](https://alyle-ui.firebaseapp.com/components/resizing-cropping-images)
