### ISSUE TITLE
How can I change Image size width and height?

### ISSUE THREAD

**Issue by sharmaprashant232** [Enlcxx/angular2-resizing-cropping-image#11]
Hello! There is always fixed width and height of image 230x150.
I want to change it. 
![image](https://user-images.githubusercontent.com/36185480/36476479-088675ae-1724-11e8-8a63-d56da16b09a7.png)
I thought importing ResizingCroppingImagesComponent in my component and I can change default values of that variables but when I did this, I got error:
No providers so I added it in providers in my module. Then I got error No providers for ElementRef.
How to solve this issue?
Please help me.

**Comment by alyleui** [comment]
Hi! @sharmaprashant232, I'm sorry for the delay, there is a new version of this module

[demo](https://alyle-ui.firebaseapp.com/component/resizing-cropping-images)

example:

```ts
@ViewChild(LyResizingCroppingImages) img: LyResizingCroppingImages;
 myConfig: LyResizingCroppingImagesConfig = {
  width: 150, // Default `250`
  height: 150 // Default `200`
};
```
