### ISSUE TITLE
angular2-resizing-cropping-image plugin reusability.

### ISSUE THREAD

**Issue by sarath3940** [Enlcxx/angular2-resizing-cropping-image#13]
Can I use angular2-resizing-cropping-image plugin for cropping two images, one at a time??

![doubt](https://user-images.githubusercontent.com/37688535/37891364-b7683620-30f1-11e8-8055-3b7e0cfa6a92.png)

**Comment by alyleui** [comment]
Hi! @sarath3940, of course it can

example:

```html
...
<ly-cropping #cropping1 [config]="myConfig"></ly-cropping>
<button (click)="cropping1.crop()">crop 1</button>

<ly-cropping #cropping2 [config]="myConfig"></ly-cropping>
<button (click)="cropping2.crop()">crop 2</button>

<button (click)="cropAll()">crop All</button>
or
<button (click)="cropping1.crop();cropping2.crop()">crop All</button>
```

```ts
...
export class ResizingCroppingImagesExample01Component {
  ...
  @ViewChildren(LyResizingCroppingImages) imgs: QueryList<LyResizingCroppingImages>;
  ...
  ngAfterViewInit() {
    this.imgs.forEach(img => console.log(img));
  }
  cropAll() {
    this.imgs.forEach(img => img.crop());
  }
}
```

**Comment by sarath3940** [comment]
Thank you! @alyleui. It worked. :)

**Comment by sarath3940** [comment]
Hi. As you specified: 
<button (click)="cropping1.crop();cropping2.crop()">crop All</button>

".crop()" is an inbuilt method. Can I use a user defined method like:

<button (click)="cropping1.cropUser()">crop</button>

Please let me know. I have tried doing that. And it's throwing an error.
![error](https://user-images.githubusercontent.com/37688535/37948243-e0e70632-31ac-11e8-8b81-1923db597159.png)

**Comment by alyleui** [comment]
".crop()" is an method of `LyResizingCroppingImages`

**Comment by alyleui** [comment]
Could you create a method in your component

```ts
export class ResizingCroppingImagesExample01Component {
  ...
  @ViewChildren(LyResizingCroppingImages) imgs: QueryList<LyResizingCroppingImages>;
  ...
  ngAfterViewInit() {
    this.imgs.forEach(img => console.log(img));
  }
  cropAll() {
    this.imgs.forEach(img => img.crop());
  }
  cropImg1() {
    this.imgs.first.crop();
  }
  cropImg2() {
    this.imgs.last.crop();
  }
}
```

```html
<button (click)="cropImg1()">crop image 1</button>
<button (click)="cropImg2()">crop image 2</button>
```

**Comment by sarath3940** [comment]
IT WORKED. Thank you dude, once again. And thank's for your quick response.
