### ISSUE TITLE
How to increase the resolution of the cropped image.

### ISSUE THREAD

**Issue by sarath3940** [Enlcxx/angular2-resizing-cropping-image#14]
I am using the alyle-ui for image-cropping, and every thing is working perfectly fine. But, the resulting image has a small resolution. I have tried to change height and width in both css, and config part in main file. But, it resulted in occupying a huge portion of the  screen. I want the cropping functionality to be shown in a small space, but the resulting image should have higher resolution. Is this possible. If yes, can you please help me with this issue. 
Thank you.
![ts](https://user-images.githubusercontent.com/37688535/38162605-92958c44-3501-11e8-9c72-4b71a265ae2c.png)
![css](https://user-images.githubusercontent.com/37688535/38162606-92c38356-3501-11e8-89a3-77cd1ada6bd8.png)

**Comment by alyleui** [comment]
I will add extra options

1. Manual configuration for the output

```ts
myConfig = {
   // view cropping
   width: 300,
   heigth: 250
   // output
   output: {
     width: 720,
     heigth: 600
   }
}
```

2. Configuration to maintain the resolution of the view
For now this is by default

```ts
import { LyResizingCroppingImages, LyResizingCroppingImagesConfig, LyResolutionDefault } from 'alyle-ui/resizing-cropping-images';
...
myConfig: LyResizingCroppingImagesConfig = {
   ...
   output: LyResolutionDefault
}
```

3. Configuration to maintain the resolution of the original image
I think this would be by default, since this would maintain the same resolution of the image, it's as if it would only be cropped
```ts
import { LyResizingCroppingImages, LyResizingCroppingImagesConfig, LyResolutionOriginalImage } from 'alyle-ui/resizing-cropping-images';
...
myConfig = {
   ...
   output: LyResolutionOriginalImage
}
```

What do you think? This feature will be implemented in a few days.

**Comment by sarath3940** [comment]
Yes. That would be great.

**Comment by alyleui** [comment]
demo [v1.6.0-beta.3](https://alyle-ui.firebaseapp.com/component/resizing-cropping-images)

**Comment by sarath3940** [comment]
That's wonderful. But, where can I find "ImageResolution" mentioned in the import section? I have installed the new package.

**Comment by sarath3940** [comment]
That's awesome dude. You made my project a little more beautiful. Thank's a lot..
