### ISSUE TITLE
How to restrict ".GIF" format?

### ISSUE THREAD

**Issue by sarath3940** [Enlcxx/angular2-resizing-cropping-image#15]
Hi there. As if now, the cropper is accepting ".gif" format as well. I don't want that to happen. What should I do?

**Comment by alyleui** [comment]
Hi!
Try this

```html
<input type="file" accept="image/jpeg, image/png" />
```
> In some browsers it does not usually work, in the next version I will add a filter.

**Comment by sarath3940** [comment]
Yes, I have tried this. What's happening is, we can't see the .gif format file's while selecting the image in File Explorer(because we have customized the file format that should be displayed). But, if we select "All Files", and if we select a .gif file, it is getting loaded. I don't want that to happen. Is their any solution. Please let me know!!
![1](https://user-images.githubusercontent.com/37688535/38538375-1842ede4-3cb1-11e8-8b35-05e998a1b9f9.png)
![2](https://user-images.githubusercontent.com/37688535/38538376-186ffc26-3cb1-11e8-9bf0-dff23990b9e1.png)
![3](https://user-images.githubusercontent.com/37688535/38538377-1899bb42-3cb1-11e8-8a2d-9ca4459fbd63.png)

**Comment by alyleui** [comment]
Replace `cropping.selectInputEvent($event)` to `filterFormat($event)`...
```html
<input #_fileInput type="file" (change)="filterFormat($event)" accept="image/*">
```

...and create filter...

```ts
...
export class myComponent {
  ...
  @ViewChild(LyResizingCroppingImages) img: LyResizingCroppingImages;
  filterFormat(event) {
    const acceptableFormats = ['image/jpeg', 'image/png'];
    const type = event.target.files[0].type;

    if (acceptableFormats.some((format) => format === type)) {
      this.img.selectInputEvent(event);
    } else {
      console.log('format not acceptable...');
    }
  }
}
```

**Comment by sarath3940** [comment]
Thank you once again. It work's.
