### ISSUE TITLE
Doubt clarification on "Zoom-Out" functionality.

### ISSUE THREAD

**Issue by sarath3940** [Enlcxx/angular2-resizing-cropping-image#17]
I have been using angular2-resizing-cropping-image for quite a while. According to the demo, the selected image can be "zoomed-out" until it reaches the configurations specified for the cropping window(as given below).

![untitled](https://user-images.githubusercontent.com/37688535/41148795-752ea5f8-6b27-11e8-8ad2-e3d8cae1867d.png)

What if I want to zoom-out further, without changing the "myConfig" settings? I hope you understand my question. If there is a solution please let me know. Thank you. Good work by-the-way.

**Comment by alyleui** [comment]
Thank you, I'm going to add a new feature, the selected image can be resized, so that I can have a better result
