### ISSUE TITLE
How to change the background color of the output image.

### ISSUE THREAD

**Issue by sarath3940** [Enlcxx/angular2-resizing-cropping-image#18]
Can you tell me how to change the background color of the output image?
![asf](https://user-images.githubusercontent.com/37688535/41157255-b8fbe064-6b42-11e8-9999-f31afa0d6ea1.png)

**Comment by alyleui** [comment]
That option is now available `@alyle/ui` v1.7.0-beta.1a7n7

**example:**

```ts
myConfig: LyResizingCroppingImagesConfig = {
    width: 150,
    height: 150,
    fill: '#ff2997' // Background color
  };
```
[demo](https://alyle-ui.firebaseapp.com/component/resizing-cropping-images)

**Comment by sarath3940** [comment]
I tried to re-install the package (npm). But it doesn't seem to work. What should I do?

**Comment by alyleui** [comment]
Does it give you an error?

**Comment by alyleui** [comment]
`npm i @alyle/ui@latest -S`

[works on Stackblitz](https://stackblitz.com/edit/resizing-cropping-image)

![area_20180610164209](https://user-images.githubusercontent.com/26355793/41206672-45cffaf8-6ccd-11e8-800a-a60181aa7676.png)

**Comment by sarath3940** [comment]
Yes. It is showing an error. 
![1](https://user-images.githubusercontent.com/37688535/41213365-7f0c86b6-6d62-11e8-9521-551d8469b3b4.png)

And my interface is still like this!!!!!
![2](https://user-images.githubusercontent.com/37688535/41213374-9786b6e4-6d62-11e8-812d-87468969e6ac.png)

I tried "npm i @alyle/ui@latest -S" as well. Am I doing anything wrong??

**Comment by alyleui** [comment]
Remember that `alyle-ui` is obsolete, now the components are in `@alyle/ui` [npm](https://www.npmjs.com/package/@alyle/ui)

see it how it is [here](https://stackblitz.com/edit/resizing-cropping-image?file=src%2Fapp%2Fapp.component.ts), if it still does not work reinstall all packages

**Comment by sarath3940** [comment]
As you said, I have reinstalled all packages.(uninstalling alyle-ui and installing alyle/ui packages). But, I got stuck with this error. Can you please look into this??
![4](https://user-images.githubusercontent.com/37688535/41223404-4a40c472-6d87-11e8-8a14-3c506f0cf644.png)

**Comment by alyleui** [comment]
I created a new project with Angular CLI
install `@alyle/ui` add cropping and all good.
try delete folder node_modules and file `package-lock.json` then `npm install`

**Comment by sarath3940** [comment]
As you did, I have done the same. Created a new project and installed @alyle/ui. But I am facing the same error.


![zdvf](https://user-images.githubusercontent.com/37688535/41275910-144b527e-6e40-11e8-9771-5f97ccd9f49d.png)
![sdfgfghn](https://user-images.githubusercontent.com/37688535/41275987-58e22d4a-6e40-11e8-8e4f-27186e289ac3.png)

**Comment by alyleui** [comment]
Could you send me the project that you created? in zip

**Comment by alyleui** [comment]
What version of node are you using? and npm

send me the result of `ng --version`

**Comment by sarath3940** [comment]
I wish I could... Thank you.

Result of ng --version.

![untitled](https://user-images.githubusercontent.com/37688535/41346507-510aa874-6f24-11e8-9c44-a29a16c8df37.png)

**Comment by alyleui** [comment]
Alyle UI only works with Angular 6

**Comment by sarath3940** [comment]
Alright. Thanks for the information.
