### ISSUE TITLE
Round Cropper

### ISSUE THREAD

**Issue by ruthansah** [Enlcxx/angular2-resizing-cropping-image#19]
Thank you for this wonderful plugin. Is there a way to configure the cropper to be round rather than square?

**Comment by Enlcxx** [comment]
use css, `border-radius: 50%;`

**Comment by sajidgangat** [comment]
Any updates on this? How can I display round cropper instead of the default square? Where should I place `border-radius: 50%;`?
@Enlcxx @alyleui

**Comment by Enlcxx** [comment]
Hi @sajidgangat sorry for the delay.

Add `border-radius: 50%;` to the result in your stylesheet, but if you want to edit the cropping area, you can add variables to theme.

e.g.

```ts
export class GlobalVariables implements PartialThemeVariables {
  ...
  ...
  imgCropper = {
    root: {
      '& {area}, & {area}::after': {
        borderRadius: '50%'
      }
    }
  };
}
```
result:

![img](https://user-images.githubusercontent.com/8032887/60375690-81bacf00-99d8-11e9-883a-dcea8d5fc678.png)

Obviously this will not make the result rounded, so do not forget to add the styles to the result.
