### ISSUE TITLE
Use with angular-cli

### ISSUE THREAD

**Issue by plul** [Enlcxx/angular2-resizing-cropping-image#2]
This looks very promising, but I cannot figure out how to use it with angular-cli.

As far as I can tell, no typings are provided? The error I get after importing the module with `import { lyResizingCroppingImagesModule } from 'angular2-resizing-cropping-image';
` is:

```
Cannot find module 'angular2-resizing-cropping-image'.
```

The contents of `node_modules/angular2-resizing-cropping-image` are:

```
index.js  index.js.map  package.json  README.md  resizing-cropping-images.js  resizing-cropping-images.js.map  resizing-cropping-images.scss
```

**Comment by Frly** [comment]
install the repo with npm
npm install angular2-resizing-cropping-image

**Comment by plul** [comment]
Thanks for replying. However, I already installed it through `npm`. My issue arrises when I attempt to import the module.

I have found an alternative solution now, which admittedly does not look as nice as `angular2-resizing-cropping-image`. I can't put more time into this issue, so I'm closing this issue. However you should be aware that there might still be a problem. Cheers.
