### ISSUE TITLE
not an NgModule

### ISSUE THREAD

**Issue by Makeon** [Enlcxx/angular2-resizing-cropping-image#3]
install with
npm install angular2-resizing-cropping-image
use with angular-cli
`import { NgModule } from '@angular/core';
import { lyResizingCroppingImagesModule } from 'angular2-resizing-cropping-image';
import { ImageUploadComponent } from './image-upload.component';

@NgModule({
  declarations: [
    ImageUploadComponent
  ],
  imports: [lyResizingCroppingImagesModule],
  exports:[
  	ImageUploadComponent
  ],
  providers: []
})
export class ImageUploadModule { }`

during compiling have reply:

> ERROR in lyResizingCroppingImagesModule is not an NgModule

**Comment by r31m4g1n3d** [comment]
^2

**Comment by Makeon** [comment]
?

**Comment by Enlcxx** [comment]
Hi @Makeon very soon I will upload a new and improved update

**Comment by Frly** [comment]
Sorry for the delay
Update the latest version
> npm i angular2-resizing-cropping-image@1.0.0-final.0 --save

This is not the end, there will be more improvements

**Comment by ayya1987** [comment]
Sorry, i am also facing same problem.

**Comment by Frly** [comment]
@ayya1987 what is the problem?
I think it's the name of the module
lyResizingCroppingImagesModule > LyResizingCroppingImagesModule
and selector
ly-cropping > ly-cropping-img

**Comment by Silvercast** [comment]
I have same issue too. very frustrating.

**Comment by imnnquy** [comment]
Same issue here

**Comment by imnnquy** [comment]
Is this repository a example of how to use the module **angular2-resizing-cropping-image**, I don't see the source code of this module here?

**Comment by carlos-hs** [comment]
For those who has this problem, just add ".forRoot()" after the module.
Ex.: LyResizingCroppingImageModule.forRoot()

This solved for me.

**Comment by Untel** [comment]
Up, have the same issue.
using forRoot() is not working for me.

**Comment by Enlcxx** [comment]
@Untel install `npm i alyle-ui`

`import { LyResizingCroppingImageModule } from 'alyle-ui/resizing-cropping-images';`

This repository will be in [Alyle-ui](https://github.com/A-l-y-l-e/Alyle-UI)
[demo](https://alyle-ui.firebaseapp.com/#/components/resizing-cropping-images)

**Comment by numerized** [comment]
Solution from @Enlcxx works but you have to rename the tag:

```<ly-cropping-img [hidden]="!Img._img.type" #Img format="png"></ly-cropping-img>```
into
```<ly-cropping [hidden]="!Img._img.type" #Img format="png"></ly-cropping>```

**Comment by numerized** [comment]
Then you have this error: 

```No provider for LyTheme!```

**Comment by alyleui** [comment]
@numerized  `LyTheme` is to set the theme color of the components
follow the example below
https://alyle-ui.firebaseapp.com/#/get-started

**Comment by Untel** [comment]
@alyleui  Can you just wrap each component in his own package ?

**Comment by alyleui** [comment]
@Untel All components will depend on AlyleUIModule
in AlyleUIModule you can set the colors for the components, you can use the components you want

**Comment by numerized** [comment]
@alyleui something is missing in your doc, I've followed exactly what you are showing us.

**Comment by alyleui** [comment]
@numerized Are you using Angular cli?

**Comment by alyleui** [comment]
I found the error
https://plnkr.co/edit/ApSnTe?p=preview
is rare that does not appear in [demo](https://alyle-ui.firebaseapp.com/#/components/resizing-cropping-images)

**Comment by numerized** [comment]
Thanks, I'm using Ionic3 cli

**Comment by alyleui** [comment]
I'll make it compatible with ionic3

**Comment by numerized** [comment]
YEY !

**Comment by vineez** [comment]
Resize handling is not working while scrolling for me.

**Comment by alyleui** [comment]
new version [1.4.6](https://alyle-ui.firebaseapp.com/components/resizing-cropping-images)
